# Generated by `python -m dgo_atlas.generate` from schema/config.yaml. Do not edit.
from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.11.0"
version = "0.1.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta({'default_prefix': 'dgoatlas',
     'default_range': 'string',
     'description': 'The site configuration an implementer writes in '
                    'dgo-atlas.yaml, kept separate from governance data. Anything '
                    'per-page is keyed by the IRI (or CURIE) of the object the '
                    'page is about.',
     'id': 'https://w3id.org/dgo-atlas/config',
     'imports': ['linkml:types'],
     'license': 'MIT',
     'name': 'dgo_atlas_config',
     'prefixes': {'dgoatlas': {'prefix_prefix': 'dgoatlas',
                               'prefix_reference': 'https://w3id.org/dgo-atlas/'},
                  'linkml': {'prefix_prefix': 'linkml',
                             'prefix_reference': 'https://w3id.org/linkml/'}},
     'source_file': 'config.yaml',
     'title': 'DGO Atlas site configuration'} )


class SiteConfig(ConfiguredBaseModel):
    """
    The contents of dgo-atlas.yaml.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config', 'tree_root': True})

    dgo_version: str = Field(default=..., description="""The Data Governance Ontology release to use, as its tag (e.g. \"0.1.0\"). Its schema is imported from the DGO repository's dist/dgo.yaml at that tag. Quote it, or YAML may read it as a number.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    dgo_source: Optional[str] = Field(default=None, description="""Import DGO from here instead of the release URL: a URL, or a path relative to dgo-atlas.yaml, to a single-file DGO schema (for a mirror, a fork, or offline builds). dgo_version still names the release.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    title: str = Field(default=..., description="""The site's name, shown in the header and every page title.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    organization: Optional[str] = Field(default=None, description="""The organization the site belongs to, shown under the title.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    description: Optional[str] = Field(default=None, description="""One sentence describing the site, used on the landing page and in search results.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    contact_email: Optional[str] = Field(default=None, description="""Where readers report a problem with a definition.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    base_path: Optional[str] = Field(default="/", description="""Where the site is served from: \"/\" for a custom domain, \"/<repo>/\" for a GitHub Pages project site. Only the 404 page uses it.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig'], 'ifabsent': 'string(/)'} })
    show_identifiers: Optional[bool] = Field(default=True, description="""Show the Identifier panel (id, expanded IRI, DGO class) on term, council, person and organization pages. Set false to hide it.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig'], 'ifabsent': 'True'} })
    prefixes: dict[str, Union[str, Prefix]] = Field(default=..., description="""The instance namespaces used in governance data, as `prefix: namespace`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    paths: Optional[Paths] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    repository: Optional[Repository] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    suggest_change_url: Optional[str] = Field(default=None, description="""A URL that starts a change request. The term's CURIE is appended, URL encoded, so end it with a query parameter such as `&term=`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    brand: Optional[Brand] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    pages: Optional[dict[str, Union[str, PageSetting]]] = Field(default=None, description="""Per-page settings keyed by the IRI or CURIE the page is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })
    text: Optional[dict[str, Union[str, TextOverride]]] = Field(default=None, description="""Replacement wording for the site, keyed by text key (e.g. `term.history: Change log`). Run `dgo-atlas text` to list every key and its default.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SiteConfig']} })

    @field_validator('dgo_version')
    def pattern_dgo_version(cls, v):
        pattern=re.compile(r"^[0-9A-Za-z][0-9A-Za-z._-]*$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid dgo_version format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid dgo_version format: {v}"
            raise ValueError(err_msg)
        return v


class Prefix(ConfiguredBaseModel):
    """
    An instance namespace used in governance data, written as `prefix: namespace` (e.g. `acme: https://data.acme.example/`).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config'})

    prefix: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Prefix']} })
    namespace: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Prefix']} })


class Paths(ConfiguredBaseModel):
    """
    Where things live, relative to dgo-atlas.yaml.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config'})

    data: Optional[str] = Field(default="governance", description="""Directory of governance YAML files (searched recursively).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Paths'], 'ifabsent': 'string(governance)'} })
    content: Optional[str] = Field(default="content", description="""Directory of authored Markdown pages.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Paths'], 'ifabsent': 'string(content)'} })
    output: Optional[str] = Field(default="site", description="""Directory the site is built into. Emptied on every build.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Paths'], 'ifabsent': 'string(site)'} })


class Repository(ConfiguredBaseModel):
    """
    The implementer's source repository, for \"view source\" links. Omit it and the links are left off.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config'})

    url: str = Field(default=..., description="""Repository web URL, e.g. https://github.com/acme/glossary.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Repository']} })
    branch: Optional[str] = Field(default="main", json_schema_extra = { "linkml_meta": {'domain_of': ['Repository'], 'ifabsent': 'string(main)'} })


class Brand(ConfiguredBaseModel):
    """
    Look of the site. Every field is optional.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config'})

    mark: Optional[str] = Field(default=None, description="""One or two characters shown in the header's brand mark.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand']} })
    accent: Optional[str] = Field(default=None, description="""Accent colour for links and actions, as a CSS colour (e.g. \"#6B3FA0\").""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand', 'PageSetting']} })
    accent_dark: Optional[str] = Field(default=None, description="""Accent colour used in dark mode; defaults to a lightened accent.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand']} })
    fonts_url: Optional[str] = Field(default=None, description="""A Google Fonts (or other) stylesheet URL loading the fonts named below.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand']} })
    display_font: Optional[str] = Field(default=None, description="""CSS font-family for headings.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand']} })
    body_font: Optional[str] = Field(default=None, description="""CSS font-family for body text.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand']} })
    serif_font: Optional[str] = Field(default=None, description="""CSS font-family for definitions and ledes.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand']} })


class PageSetting(ConfiguredBaseModel):
    """
    Settings for one page, keyed by the IRI or CURIE of what it is about.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config'})

    about: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['PageSetting']} })
    accent: Optional[str] = Field(default=None, description="""Accent colour for links and actions, as a CSS colour (e.g. \"#6B3FA0\").""", json_schema_extra = { "linkml_meta": {'domain_of': ['Brand', 'PageSetting']} })


class TextOverride(ConfiguredBaseModel):
    """
    Replacement wording for one text key, written as `key: wording` (e.g. `term.history: Change log`). `dgo-atlas text` lists the keys.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/config'})

    key: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TextOverride']} })
    value: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TextOverride']} })


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
SiteConfig.model_rebuild()
Prefix.model_rebuild()
Paths.model_rebuild()
Repository.model_rebuild()
Brand.model_rebuild()
PageSetting.model_rebuild()
TextOverride.model_rebuild()
