# Generated by `python -m dgo_atlas.generate` from schema/viewmodel.yaml. Do not edit.
from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.11.0"
version = "0.1.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta({'default_prefix': 'dgoatlas',
     'default_range': 'string',
     'description': 'The shape of the pages the site renders. The derivation turns '
                    'validated governance data into one Site document, which is '
                    'validated against this schema before anything is rendered. '
                    "Unlike governance data, it holds derived facts: a term's "
                    'state, its domain, its governing councils, narrower terms. '
                    'Every page carries the IRI of what it is about.',
     'id': 'https://w3id.org/dgo-atlas/viewmodel',
     'imports': ['linkml:types'],
     'license': 'MIT',
     'name': 'dgo_atlas_viewmodel',
     'prefixes': {'dgo': {'prefix_prefix': 'dgo',
                          'prefix_reference': 'https://w3id.org/dgo/'},
                  'dgoatlas': {'prefix_prefix': 'dgoatlas',
                               'prefix_reference': 'https://w3id.org/dgo-atlas/'},
                  'linkml': {'prefix_prefix': 'linkml',
                             'prefix_reference': 'https://w3id.org/linkml/'}},
     'source_file': '/Users/jamesgeiger/Repositories/dgo-atlas/src/dgo_atlas/schema/viewmodel.yaml',
     'title': 'DGO Atlas view model'} )

class TermState(str, Enum):
    """
    A published term's state (provisional rule; see derive.term_state). Terms with no recorded creation, or a rejected one, are not published, so they have no state here.
    """
    approved = "approved"
    """
    Its creation reached an approved boundary.
    """
    proposed = "proposed"
    """
    Its creation is still open.
    """
    deprecated = "deprecated"
    """
    A deprecation of it reached an approved boundary.
    """


class Outcome(str, Enum):
    open = "open"
    approved = "approved"
    rejected = "rejected"


class ProcessKind(str, Enum):
    term_creation = "term_creation"
    term_modification = "term_modification"
    term_deprecation = "term_deprecation"


class BoundaryKind(str, Enum):
    drafted = "drafted"
    submitted_for_review = "submitted_for_review"
    approved = "approved"
    rejected = "rejected"


class AgentKind(str, Enum):
    person = "person"
    organization = "organization"
    council = "council"



class Site(ConfiguredBaseModel):
    """
    Every page of one site.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel', 'tree_root': True})

    glossaries: Optional[list[GlossaryPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site']} })
    domains: Optional[list[DomainPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'GlossaryPage']} })
    subject_areas: Optional[list[SubjectAreaPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'DomainPage']} })
    terms: Optional[list[TermPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'SubjectAreaPage']} })
    councils: Optional[list[CouncilPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'ProcessPage']} })
    agents: Optional[list[AgentPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site']} })
    processes: Optional[list[ProcessPage]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site']} })


class Page(ConfiguredBaseModel):
    """
    Anything with its own page (or anchor) on the site.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True, 'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class Ref(ConfiguredBaseModel):
    """
    A link to another page.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })
    state: Optional[TermState] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Ref', 'TermPage']} })
    kind: Optional[AgentKind] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Ref', 'AgentPage']} })


class GlossaryPage(Page):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'domains': {'inlined': True,
                                    'inlined_as_list': True,
                                    'name': 'domains',
                                    'range': 'Ref'}}})

    domains: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'GlossaryPage']} })
    term_count: Optional[int] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['GlossaryPage', 'DomainPage', 'GovernedArea']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class DomainPage(Page):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'subject_areas': {'inlined': True,
                                          'inlined_as_list': True,
                                          'name': 'subject_areas',
                                          'range': 'Ref'}}})

    glossary: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['DomainPage', 'SubjectAreaPage', 'TermPage']} })
    subject_areas: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'DomainPage']} })
    term_count: Optional[int] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['GlossaryPage', 'DomainPage', 'GovernedArea']} })
    accent: Optional[str] = Field(default=None, description="""A CSS colour for this page's cards, from the site config.""", json_schema_extra = { "linkml_meta": {'domain_of': ['DomainPage', 'SubjectAreaPage']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class SubjectAreaPage(Page):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'domain': {'name': 'domain', 'required': True},
                        'terms': {'inlined': True,
                                  'inlined_as_list': True,
                                  'name': 'terms',
                                  'range': 'Ref'}}})

    glossary: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['DomainPage', 'SubjectAreaPage', 'TermPage']} })
    domain: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['SubjectAreaPage', 'TermPage', 'GovernedArea']} })
    terms: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'SubjectAreaPage']} })
    accent: Optional[str] = Field(default=None, description="""A CSS colour for this page's cards, from the site config.""", json_schema_extra = { "linkml_meta": {'domain_of': ['DomainPage', 'SubjectAreaPage']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class TermPage(Page):
    """
    One glossary term with every fact a reader needs.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'domain': {'name': 'domain', 'required': True},
                        'glossary': {'name': 'glossary', 'required': True},
                        'state': {'name': 'state', 'required': True},
                        'subject_area': {'name': 'subject_area', 'required': True}}})

    name: Optional[str] = Field(default=None, description="""The term's `label`, when it differs from the display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    alt_labels: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    definition: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    definition_source: Optional[SourceRef] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    semantic_type: Optional[SemanticType] = Field(default=None, description="""The external class the term denotes.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    state: TermState = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Ref', 'TermPage']} })
    glossary: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['DomainPage', 'SubjectAreaPage', 'TermPage']} })
    subject_area: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage', 'GovernedArea']} })
    domain: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['SubjectAreaPage', 'TermPage', 'GovernedArea']} })
    responsibilities: Optional[list[Responsibility]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage', 'CouncilPage', 'AgentPage']} })
    governing_councils: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    pending_changes: Optional[list[Change]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    history: Optional[list[HistoryEntry]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    successor: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    predecessors: Optional[list[Ref]] = Field(default=None, description="""Terms whose replaced_by is this term.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    broader: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    ancestors: Optional[list[Ref]] = Field(default=None, description="""Every term reached by walking broader, nearest first.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    narrower: Optional[list[Ref]] = Field(default=None, description="""Terms whose broader includes this term.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    related: Optional[list[Ref]] = Field(default=None, description="""Related terms, read in both directions.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    value_of: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    values: Optional[list[Ref]] = Field(default=None, description="""Terms whose value_of is this term.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    source_file: Optional[str] = Field(default=None, description="""The governance file the object is defined in, relative to the repository.""", json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class SourceRef(ConfiguredBaseModel):
    """
    Where a definition was drawn from.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class SemanticType(ConfiguredBaseModel):
    """
    The external class a term denotes, with the label read from that class. Only about and iri are known when the lookup fails.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'label': {'name': 'label', 'required': False}}})

    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    label: Optional[str] = Field(default=None, description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })
    ontology: Optional[str] = Field(default=None, description="""The short name of the ontology that defines a class, e.g. BFO.""", json_schema_extra = { "linkml_meta": {'domain_of': ['SemanticType']} })


class Responsibility(ConfiguredBaseModel):
    """
    A governance role held with respect to a term, and who bears it.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    role: str = Field(default=..., description="""Slug of the role kind, e.g. owner or chair.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    role_label: str = Field(default=..., description="""DGO's name for the role kind, e.g. subject matter expert.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    role_iri: str = Field(default=..., description="""The DGO class IRI of the role kind.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    term: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility']} })
    bearer: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility']} })


class Change(ConfiguredBaseModel):
    """
    A term lifecycle process (creation, modification or deprecation).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })
    process_kind: ProcessKind = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Change', 'HistoryEntry']} })
    process_label: str = Field(default=..., description="""DGO's name for the process kind, e.g. term modification.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Change', 'HistoryEntry']} })
    outcome: Outcome = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Change']} })


class HistoryEntry(ConfiguredBaseModel):
    """
    One status boundary of one of the term's lifecycle processes.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'process': {'inlined': True,
                                    'name': 'process',
                                    'range': 'Change'}}})

    occurred_on: date = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['HistoryEntry']} })
    process: Change = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['HistoryEntry']} })
    process_kind: ProcessKind = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Change', 'HistoryEntry']} })
    process_label: str = Field(default=..., description="""DGO's name for the process kind, e.g. term modification.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Change', 'HistoryEntry']} })
    boundary_kind: BoundaryKind = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['HistoryEntry']} })
    boundary_label: str = Field(default=..., description="""DGO's name for the boundary kind, e.g. submitted for review.""", json_schema_extra = { "linkml_meta": {'domain_of': ['HistoryEntry']} })


class CouncilPage(Page):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'responsibilities': {'inlined': True,
                                             'inlined_as_list': True,
                                             'name': 'responsibilities',
                                             'range': 'Responsibility'}}})

    participates_in: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['CouncilPage']} })
    process_chain: Optional[list[Ref]] = Field(default=None, description="""The process the council participates in and every process it is part of, innermost first.""", json_schema_extra = { "linkml_meta": {'domain_of': ['CouncilPage']} })
    members: Optional[list[Seat]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['CouncilPage']} })
    responsibilities: Optional[list[Responsibility]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage', 'CouncilPage', 'AgentPage']} })
    governed_terms: Optional[list[Ref]] = Field(default=None, description="""Terms whose lifecycle processes fall under this council.""", json_schema_extra = { "linkml_meta": {'domain_of': ['CouncilPage']} })
    governed_areas: Optional[list[GovernedArea]] = Field(default=None, description="""Subject areas of the council's governed terms and the terms it holds roles on, by domain.""", json_schema_extra = { "linkml_meta": {'domain_of': ['CouncilPage']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class GovernedArea(ConfiguredBaseModel):
    """
    A subject area holding terms a council governs or holds a role on, so the council page can point to the area instead of re-listing its terms.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'domain': {'name': 'domain', 'required': True},
                        'subject_area': {'name': 'subject_area', 'required': True},
                        'term_count': {'description': "How many of the area's terms "
                                                      'fall to this council.',
                                       'name': 'term_count',
                                       'required': True}}})

    subject_area: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage', 'GovernedArea']} })
    domain: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['SubjectAreaPage', 'TermPage', 'GovernedArea']} })
    term_count: int = Field(default=..., description="""How many of the area's terms fall to this council.""", json_schema_extra = { "linkml_meta": {'domain_of': ['GlossaryPage', 'DomainPage', 'GovernedArea']} })
    roles: Optional[list[RoleKind]] = Field(default=None, description="""The kinds of role the council holds on terms in this area.""", json_schema_extra = { "linkml_meta": {'domain_of': ['GovernedArea']} })


class RoleKind(ConfiguredBaseModel):
    """
    A kind of role, without its bearer or term.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    role: str = Field(default=..., description="""Slug of the role kind, e.g. owner or chair.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    role_label: str = Field(default=..., description="""DGO's name for the role kind, e.g. subject matter expert.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    role_iri: str = Field(default=..., description="""The DGO class IRI of the role kind.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })


class Seat(ConfiguredBaseModel):
    """
    A council member and the council roles they hold on it.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    member: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Seat']} })
    council: Ref = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Seat']} })
    council_roles: Optional[list[CouncilRoleHeld]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Seat']} })


class CouncilRoleHeld(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel'})

    role: str = Field(default=..., description="""Slug of the role kind, e.g. owner or chair.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    role_label: str = Field(default=..., description="""DGO's name for the role kind, e.g. subject matter expert.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })
    role_iri: str = Field(default=..., description="""The DGO class IRI of the role kind.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Responsibility', 'RoleKind', 'CouncilRoleHeld']} })


class AgentPage(Page):
    """
    A person or organization.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'memberships': {'inlined': True,
                                        'inlined_as_list': True,
                                        'name': 'memberships',
                                        'range': 'Seat'}}})

    kind: Optional[AgentKind] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Ref', 'AgentPage']} })
    email: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['AgentPage']} })
    job_title: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['AgentPage']} })
    memberships: Optional[list[Seat]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['AgentPage']} })
    organization_members: Optional[list[Ref]] = Field(default=None, description="""The people and organizations that are members of an organization.""", json_schema_extra = { "linkml_meta": {'domain_of': ['AgentPage']} })
    member_of: Optional[list[Ref]] = Field(default=None, description="""The organizations a person or organization is a member of.""", json_schema_extra = { "linkml_meta": {'domain_of': ['AgentPage']} })
    responsibilities: Optional[list[Responsibility]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['TermPage', 'CouncilPage', 'AgentPage']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


class ProcessPage(Page):
    """
    A data governance process (not a term lifecycle process).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://w3id.org/dgo-atlas/viewmodel',
         'slot_usage': {'councils': {'inlined': True,
                                     'inlined_as_list': True,
                                     'name': 'councils',
                                     'range': 'Ref'}}})

    parent: Optional[Ref] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['ProcessPage']} })
    children: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['ProcessPage']} })
    councils: Optional[list[Ref]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Site', 'ProcessPage']} })
    about: str = Field(default=..., description="""The CURIE of the governed object this page or link is about.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SemanticType', 'Change']} })
    iri: str = Field(default=..., description="""The expanded IRI of the governed object (or the source).""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'SourceRef', 'SemanticType']} })
    url: Optional[str] = Field(default=None, description="""Site-relative path of the page, e.g. terms/clinical-trial.html.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref']} })
    label: str = Field(default=..., description="""The display label.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Page', 'Ref', 'SourceRef', 'SemanticType', 'Change']} })


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
Site.model_rebuild()
Page.model_rebuild()
Ref.model_rebuild()
GlossaryPage.model_rebuild()
DomainPage.model_rebuild()
SubjectAreaPage.model_rebuild()
TermPage.model_rebuild()
SourceRef.model_rebuild()
SemanticType.model_rebuild()
Responsibility.model_rebuild()
Change.model_rebuild()
HistoryEntry.model_rebuild()
CouncilPage.model_rebuild()
GovernedArea.model_rebuild()
RoleKind.model_rebuild()
Seat.model_rebuild()
CouncilRoleHeld.model_rebuild()
AgentPage.model_rebuild()
ProcessPage.model_rebuild()
