"""Regenerate the code and JSON Schema derived from the middleware's own schemas.

    uv run python -m dgo_atlas.generate          # rewrite the generated files
    uv run python -m dgo_atlas.generate --check  # exit 1 if any has drifted

These don't depend on DGO, so they are committed. Everything derived from the
authoring template (its pydantic model and editor JSON Schema) depends on the
project's DGO release and is generated at runtime instead (see dgo.py).

This is a developer tool, not a `dgo-atlas` command: it rewrites files inside
the package, which in an implementer's install would be site-packages.
tests/test_generated.py checks that nothing is stale.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Annotated

import typer

from .console import fail, say
from .resources import CONFIG_JSON_SCHEMA, CONFIG_SCHEMA, MODELS_DIR, VIEWMODEL

HEADER = "# Generated by `python -m dgo_atlas.generate` from {source}. Do not edit.\n"


def _run(args: list[str]) -> str:
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{' '.join(args[:1])} failed:\n{result.stderr}")
    return result.stdout if result.stdout.endswith("\n") else result.stdout + "\n"


def outputs() -> dict[Path, str]:
    """Every generated file and the content it should have."""
    out: dict[Path, str] = {}
    for schema, module in ((VIEWMODEL, "viewmodel"), (CONFIG_SCHEMA, "config")):
        code = _run(["gen-pydantic", str(schema)])
        out[MODELS_DIR / f"{module}.py"] = HEADER.format(source=f"schema/{schema.name}") + code
    out[CONFIG_JSON_SCHEMA] = _run(["gen-json-schema", "--top-class", "SiteConfig", str(CONFIG_SCHEMA)])
    if EXAMPLE_CONFIG.parent.joinpath("pyproject.toml").exists():  # a source checkout, not an install
        out[EXAMPLE_CONFIG] = example_config()
    return out


# ---------------------------------------------------------------- dgo-atlas.example.yaml

# At the root of the source repository.
EXAMPLE_CONFIG = Path(__file__).resolve().parents[2] / "dgo-atlas.example.yaml"

# Settings that have no schema default but are given one by the code when left
# out, and where that value lives. Read from the source so this can't drift.
def _applied_defaults() -> dict[str, tuple[object, str]]:
    import re

    from . import dgo
    from .render import DEFAULT_FONTS_URL
    from .resources import STATIC

    css = (STATIC / "site.css").read_text(encoding="utf-8")

    def var(name):
        return re.search(rf"--{name}:\s*([^;]+);", css).group(1).strip()

    return {
        "dgo_version": (dgo.TESTED_VERSIONS[-1], "required; shown is the newest release this version of DGO Atlas is tested with"),
        "title": (None, "required"),
        "mark": (None, "unset by default: the initials of the title are used"),
        "accent": (var("accent"), "the default, from site.css"),
        "accent_dark": (None, "unset by default: the accent mixed half and half with white is used"),
        "fonts_url": (DEFAULT_FONTS_URL, "the default stylesheet"),
        "display_font": (var("font-display"), "the default, from site.css"),
        "body_font": (var("font-body"), "the default, from site.css"),
        "serif_font": (var("font-serif"), "the default, from site.css"),
    }


def _yaml_value(value) -> str:
    """A YAML scalar: blank for unset, double-quoted when a plain string would misread."""
    import json

    import yaml

    if value is None:
        return ""  # `key:` reads as unset
    if isinstance(value, bool):
        return "true" if value else "false"
    text = yaml.safe_dump(value, allow_unicode=True, width=10_000).strip().removesuffix("...").strip()
    plain_ok = not text.startswith(("'", '"')) and yaml.safe_load(text) == value
    looks_numeric = all(c.isdigit() or c == "." for c in str(value))
    return text if plain_ok and not looks_numeric else json.dumps(value, ensure_ascii=False)


def _wrap(text: str, indent: str, width: int = 80) -> list[str]:
    import textwrap

    prefix = f"# {indent}# "
    return textwrap.wrap(" ".join(text.split()), width=width, initial_indent=prefix, subsequent_indent=prefix)


def example_config() -> str:
    """Every dgo-atlas.yaml setting, commented out, at its default."""
    import yaml

    from .text import defaults as text_defaults

    schema = yaml.safe_load(CONFIG_SCHEMA.read_text(encoding="utf-8"))
    classes, slots = schema["classes"], schema["slots"]
    applied = _applied_defaults()

    lines = [
        "# # dgo-atlas.example.yaml: every setting dgo-atlas.yaml accepts, at its default.",
        "# #",
        "# # Generated by `python -m dgo_atlas.generate` from src/dgo_atlas/schema/config.yaml",
        "# # and src/dgo_atlas/text.yaml. Do not edit; change those and regenerate.",
        "# #",
        "# # Everything is commented out. Lines starting `# # ` explain; lines starting",
        "# # `# ` are settings. To use a block (or the whole file), remove one `# ` from",
        "# # each of its lines (Cmd+/ or Ctrl+/ in most editors): the settings become",
        "# # YAML and the explanations stay comments. Only dgo_version, title and",
        "# # prefixes are required; leave out anything else to keep its default.",
        "",
    ]

    def emit(name: str, spec: dict, indent: str) -> None:
        spec = spec or {}
        description = spec.get("description")
        note = []
        if spec.get("required"):
            note.append("required")
        default = None
        if "ifabsent" in spec:
            raw = spec["ifabsent"]  # string(x), or a bare YAML value such as true
            default = raw[len("string("):-1] if isinstance(raw, str) and raw.startswith("string(") else raw
        elif name in applied:
            default, why = applied[name]
            note = [why]
        if description:
            lines.extend(_wrap(description + (f" ({'; '.join(note)})" if note else ""), indent))
        elif note:
            lines.extend(_wrap(f"({'; '.join(note)})", indent))

        range_ = spec.get("range")
        if range_ in classes and spec.get("multivalued"):
            # A keyed map: prefixes, pages, text.
            if name == "text":
                lines.append(f"# {indent}{name}:")
                section = None
                for key, value in text_defaults().items():
                    top = key.split(".", 1)[0]
                    if top != section:
                        if section is not None:
                            lines.append("#")
                        section = top
                    lines.append(f"# {indent}  {key}: {_yaml_value(value)}")
            elif name == "prefixes":
                lines.append(f"# {indent}{name}:")
                lines.extend(_wrap("One entry per prefix your ids use; this one is an example, with no default.", indent + "  "))
                lines.append(f"# {indent}  org: https://data.example.org/governance/")
            elif name == "pages":
                lines.append(f"# {indent}{name}: {{}}")
                lines.extend(_wrap("No per-page settings by default. Each entry is keyed by an id, for example:", indent))
                lines.append(f"# {indent}# pages:")
                lines.append(f"# {indent}#   org:research:")
                for slot in classes[range_]["slots"]:
                    if slot != "about":
                        lines.append(f"# {indent}#     {slot}: \"#2E7D6B\"")
        elif range_ in classes:
            lines.append(f"# {indent}{name}:")
            for slot in classes[range_]["slots"]:
                emit(slot, slots.get(slot), indent + "  ")
        else:
            lines.append(f"# {indent}{name}: {_yaml_value(default)}".rstrip())

    for name in classes["SiteConfig"]["slots"]:
        emit(name, slots.get(name), "")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def stale(*, write: bool) -> list[Path]:
    """The generated files that differ from their sources; rewrite them if `write`."""
    changed = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        if write:
            path.write_text(content, encoding="utf-8")
    return changed


app = typer.Typer(add_completion=False)


@app.command()
def main(check: Annotated[bool, typer.Option("--check", help="Write nothing; exit 1 if any file is stale.")] = False
         ) -> None:
    """Regenerate the pydantic models and JSON Schema from the middleware's LinkML schemas."""
    changed = stale(write=not check)
    if check and changed:
        raise typer.Exit(fail("Out of date (run `uv run python -m dgo_atlas.generate`):", [p.name for p in changed]))
    for path in changed:
        say(f"wrote {path.name}")


if __name__ == "__main__":
    app()
